### PR TITLE
update libsqsh to v1.0.0

### PR DESCRIPTION
**Pull request by Gottox**
I wasn't able to test Filer itself as a few tools were missing, but could you try if this fixes the issue?

image

### CODE REVIEW

**Comment by probonopd** [comment]
Will do. In the meantime, `sudo touch /usr/local/bin/open ; sudo chmod +x /usr/local/bin/open` should get it past that error.

**Comment by Gottox** [comment]
image

**Comment by probonopd** [comment]
Oh, right. My test there is more thorough than I remembered. You can get the proper one from https://github.com/helloSystem/launch/releases/tag/continuous. Sorry for the hassle.

**Comment by Gottox** [comment]
Okay, from my tests, it seems to work.

**Comment by probonopd** [comment]
Hmmm....

I am still getting 

```
CustomFileIconProvider::icon:  "/home/user/Desktop/appimagetool-730-x86_64.AppImage"
offset: 594264 for file "/home/user/Desktop/appimagetool-730-x86_64.AppImage"
Extracting AppImage icon for file "/home/user/Desktop/appimagetool-730-x86_64.AppImage"
Assertion failed: (acc == 0), function cx_rc_map_cleanup, file ../subprojects/cextras-887bee6835d5fa8213a8f9ffbdf3a26f119983a3/lib/collection/rc_map.c, line 222.
```

This is what I did:

```
git clone https://github.com/Gottox/libsqsh
cd libsqsh
git checkout v1.0.0
meson setup build -Dwerror=false -Dexamples=false -Dcurl=disabled -Dzlib=enabled -Dlz4=disabled -Dlzma=disabled -Dzstd=enabled -Dthreads=enabled -Ddoc=false\n
cd build
meson compile
sudo meson install
cd /tmp
git clone https://github.com/Gottox/Filer
cd Filer
git checkout libsqsh-1.0.0
mkdir build
cd build
cmake ..
make -j8
launch ./Filer.app
```

**Comment by Gottox** [comment]
Looking into it tomorrow.

**Comment by Gottox** [comment]
The System is Ubuntu or FreeBSD?

**Comment by probonopd** [comment]
I am using FreeBSD:
https://github.com/helloSystem/ISO/releases/tag/experimental-13.2

**Comment by Gottox** [comment]
I can't reproduce it on Linux, okay, let me setup fbsd then.

**Comment by probonopd** [comment]
Sorry for the extra hassle. In case you want to use helloSystem, don't forget to also install the Developer Tools from developer.img after you installed the helloSystem Live ISO. Thanks for your patience and support.

**Comment by probonopd** [comment]
To kill the (old) Filer:
1. Run `killall daemon` (otherwise the Filer automatically restarts when it gets killed)
2. Press Ctrl-Alt-Esc, then click on the desktop background
3. Now you can run the new Filer (the one under development)

**Comment by Gottox** [comment]
Can reproduce. Let's find out what's wrong.

**Comment by Gottox** [comment]
\*sigh\*

```diff
diff --git a/src/SqshArchiveReader.cpp b/src/SqshArchiveReader.cpp
index b665a01..f7389a6 100644
--- a/src/SqshArchiveReader.cpp
+++ b/src/SqshArchiveReader.cpp
@@ -73,7 +73,6 @@ QByteArray SqshArchiveReader::readFileFromArchive(const QString& sqsh_file, cons
     QByteArray file_path_bytes = file_path.toUtf8();
     const char* file_path_cstr = file_path_bytes.constData();
 
-    struct SqshFile* file = NULL;
     uint8_t *file_data = NULL;
     size_t file_size = 0;
     QByteArray data; // Declare the 'data' variable here
@@ -87,11 +86,6 @@ QByteArray SqshArchiveReader::readFileFromArchive(const QString& sqsh_file, cons
         goto out;
     }
 
-    file = sqsh_open(archive, file_path_cstr, &error_code); // Use 'file_path_cstr' here
-    if (error_code != 0) {
-        sqsh_perror(error_code, "sqsh_open");
-        goto out;
-    }
     file_size = sqsh_easy_file_size(archive, file_path_cstr, &error_code);
     if (error_code != 0) {
         sqsh_perror(error_code, "sqsh_easy_file_size");
```

**Comment by Gottox** [comment]
Okay, I fixed the issue. It was suprisingly easy and hiding in plain sight.

The issue why it wasn't caught on Linux was, that I compiled libsqsh with `-DNDEBUG` on that system, which disables those leak-checks.

**Comment by probonopd** [comment]
Thank you very much for your help @Gottox, this is tremendous. It is working great now! :+1:

**Pull request merged**
